<a href="https://colab.research.google.com/github/m-sarfraz/dashboard/blob/dashboard/USVR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Importing Libraries for Code***

In [ ]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.decomposition import TruncatedSVD
import warnings

***Importing first CSV file***

1.   First file containing the data of Video Details is imported
2.   Attributes which are not needed right now are droped for accuracy  and optimization of algorithm.
3.   View can be seen through head function()

In [ ]:
videos = pd.read_csv(r'VideoDetails.csv', sep=',')
videos = videos.iloc[:, :20]
videos = videos.drop(columns=['Category-id', 'video-code','url','sub'])
videos.head(20)

    video_id  ... uploaded_by_id
0         50  ...            100
1         49  ...            493
2         48  ...             44
3         47  ...            190
4         46  ...             44
5         45  ...            130
6         44  ...            124
7         43  ...             44
8         42  ...              4
9         41  ...            120
10        40  ...            100
11        39  ...              4
12        38  ...            100
13        37  ...             44
14        36  ...            120
15        35  ...            100
16        34  ...             44
17        33  ...             49
18        32  ...            120
19        31  ...             44

[20 rows x 5 columns]

***Shaping Data***
video data is shaped for matrix factorization algorithm.

In [ ]:
videos.shape

(48, 5)

***Importnig Second File***

1.   File containing the data of User/Likes/Views Details is imported
2.   Attributes which are not needed right now are droped for accuracy  and optimization of algorithm.
3.   View can be seen through head function()

In [ ]:
        ratings = pd.read_csv(r'User_videos_views_likes.csv', sep=',')
        ratings = ratings.iloc[:, :11]
        ratings = ratings.drop(columns=['product_code','product_color','color','quantity','user_email','price'])
        ratings.head(20)

      id  video_id  ...       views       likes
0    1.0        50  ...       477.0       345.0
1    2.0        49  ...       677.0   2345677.0
2    3.0        48  ...      4545.0     23423.0
3    4.0        47  ...     45646.0       342.0
4    5.0        46  ...       456.0      2546.0
5    6.0        45  ...     45456.0      4545.0
6    7.0        44  ...  45645645.0     45646.0
7    8.0        43  ...       477.0       456.0
8    9.0        42  ...       677.0     45456.0
9   10.0        41  ...      4545.0  45645645.0
10  11.0        40  ...     45646.0      4334.0
11  12.0        39  ...       456.0        10.0
12  13.0        38  ...     45456.0        11.0
13  14.0        37  ...  45645645.0        12.0
14  15.0        36  ...       477.0        13.0
15  16.0        35  ...       677.0        14.0
16  17.0        34  ...      4545.0        15.0
17  19.0        33  ...     45646.0        16.0
18  20.0        32  ...       456.0         2.0
19  21.0        31  ...     45456.0         3.0

[20 rows x 5 columns]

***Shaping Data***

In [ ]:
ratings.shape

(48, 5)

***Merging Data***

In [ ]:
        df = pd.merge(videos, ratings, on ='video_id')
        df1.head(20)

    video_id                                   attachment_title  ...  views  likes
0         50                            Gr1 L Updated Timetable  ...      3    2.0
1         49                                           الإنترنت  ...      4    3.0
2         48                               ورقة عمل نص الانطلاق  ...      5    4.0
3         47                                  ورقة عمل - إملاء   ...      3    5.0
4         46                              Comment tu t'appelles  ...      2    6.0
5         45                     الفصل الاول  / الجبر و الدوال   ...      1    7.0
6         44                                            الألوان  ...      3    8.0
7         43                                 المقدمة التساؤلية   ...      4    9.0
8         42                                              Rules  ...      5   10.0
9         41                      Ch1 Introduction to chemistry  ...      3   11.0
10        40                  3Conversation  - page:4 - AUDIO -  ...      5   12.0
11        39                                    speaking skills  ...      3   13.0
12        38                                      نداء الأثير    ...      2   14.0
13        37                        Math homework for 8-9-2020   ...      4   15.0
14        36                                          Lesson 2   ...      2   16.0
15        35  فديو عن الخليفة الثاني (عمر بن الخطاب) رضي الل...  ...      3    2.0
16        34  فصل ذكي نص استماع ( فئات تكلؤها عين الشريعة  )...  ...      2    3.0
17        33                                   شرح الازمنه مبسط  ...      1    4.0
18        32                                  حفظ سورة المطففين  ...      4    5.0
19        31                                                NaN  ...      5    6.0

[20 rows x 5 columns]

In [ ]:
        videos_matrix = df.pivot_table(index = 'likes', columns = 'video_id', values= 'views').fillna(0)
        videos_matrix.head()

video_id   18   19   20   21   22   23   24  ...   44   45   46   47   48   49   50
likes                                        ...
2.0       0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3.0       0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4.0       0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
5.0       0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
6.0       0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[5 rows x 33 columns]

In [ ]:
videos_matrix.shape

(27, 33)

In [ ]:
X = videos_matrix.values.T
X.shape

(33, 27)

In [ ]:
SVD = TruncatedSVD(n_components=12, random_state=100)
matrix = SVD.fit_transform(X)
matrix.shape

(33, 12)

In [ ]:
import warnings
warnings.filterwarnings("ignore",category =RuntimeWarning)
corr = np.corrcoef(matrix)
corr.shape

(33, 33)

In [ ]:
   # Correlation coeficient
title = videos_matrix.columns
print('             |***************************************************|')
print('             |************ALGORITHM RESULT IS HERE***************|')
print('             |***************************************************|')
title_list = list(title)
print ('from list of refined matrixes values of User/Videos/Likes:')
print('*******************************')
print (title_list)
print('*******************************')
print ('for new each new user at index:')
new_user = title_list.index(18)
corr_new_user  = corr[new_user]
print('*******************************')
print (corr_new_user)
print('*******************************')
print ('Array of Similar videos to watch will be on indexes:')
print('*******************************')
print(list(title[(corr_new_user >=0.1)]))
print('            ****************************************************************************')
print('            *** You Can Change Data from CSV File to view Different Result Good Luck ***')
print('            ****************************************************************************')

             |***************************************************|
             |************ALGORITHM RESULT IS HERE***************|
             |***************************************************|
from list of refined matrixes values of User/Videos/Likes:
*******************************
[18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
*******************************
for new each new user at index:
*******************************
[ 1.         -0.0955145  -0.31228103 -0.41640612  0.74838067 -0.09557634
 -0.09973916  0.16559294  0.05399968 -0.05307601  0.31517808 -0.05736156
  0.49553072 -0.08995082  0.08222972 -0.14563071 -0.0955145  -0.31030516
 -0.41644848  0.74838067 -0.09557634 -0.09137035  0.00264145 -0.09551455
  0.24699304 -0.19213909 -0.30686926 -0.1299478   0.09957237 -0.09073969
 -0.09551465 -0.22185667 -0.09798115]
*******************************
Array of Similar videos to watch will be on indexes:
*******************************
[18, 22, 25, 28, 30, 37, 42]
            ****************************************************************************
            *** You Can Change Data from CSV File to view Different Result Good Luck ***
            ****************************************************************************